### ISSUE TITLE
Use this package

### ISSUE THREAD

**Issue by fomvasss** [enniel/epochta#1]
Hey. Can not understand how to use. Show, please, an example use this package

**Comment by enniel** [comment]
You can use [this package](https://github.com/enniel/laravel-epochta-notification-channel) for laravel.

**Comment by fomvasss** [comment]
This enniel/epochta package does not actual?

**Comment by enniel** [comment]
You can also use so:

Add your private and public keys to your `config/services.php`:

```php
// config/services.php
...
'epochta' => [
    'sms' => [
        'public_key' => env('EPOCHTA_SMS_PUBLIC_KEY'),
        'private_key' => env('EPOCHTA_SMS_PRIVATE_KEY'),
    ],
],
...
```

And then in your code:

`\Enniel\Epocha\Facades\SMS::sendSMS([])`
